server:
  port: 8088
spring:
  mvc:
    servlet:
      load-on-startup: 1
  redis:
    port: 6379
    host: 192.168.78.128
  mail:
    host: smtp.qq.com
    username: 2677742124@qq.com
    password: nhptnaqmsohldjeb
    defalut-encoding: UTF-8




  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB
  application:
    name: nevs

  data:
    mongodb:
      uri: mongodb://192.168.78.128:27017/nevs

minio:
  url: http://192.168.78.128:9002  #对象存储服务的URL
  accessKey: TMBSFQF7T54ELZAF6DE0 #登陆账户
  secretKey: aK+XIcyr4UQ5kQWaWjQQi7islsdnwK9lfRgVmkcb #登陆密码



version: 1.0.0

ip: 192.168.135.198



